# Generated by Django 5.2.8 on 2025-12-27 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_company_contact_task_assigned_to_task_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Object created'), ('UPDATE', 'Object updated'), ('DELETE', 'Object deleted'), ('LOGIN', 'User logged in')], db_index=True, help_text='Type of action: CREATE, UPDATE, DELETE, LOGIN, etc.', max_length=20)),
                ('entity_type', models.CharField(db_index=True, help_text="Model name affected (e.g., 'Company', 'Contact', 'Deal', 'Task')", max_length=100)),
                ('entity_id', models.CharField(db_index=True, help_text='Primary key of audited object (flexible for UUID or int)', max_length=100)),
                ('old_values', models.JSONField(blank=True, default=dict, help_text='Previous field values before update', null=True)),
                ('new_values', models.JSONField(blank=True, default=dict, help_text='New field values after update', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, help_text='IPv4 or IPv6 address of request origin', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User-Agent HTTP header from request')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC timestamp of action')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action (from token auth)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'entity_type'], name='tasks_audit_action_fe2141_idx'), models.Index(fields=['user', 'created_at'], name='tasks_audit_user_id_ca8186_idx'), models.Index(fields=['entity_type', 'entity_id'], name='tasks_audit_entity__162140_idx')],
            },
        ),
    ]
