# Generated by Django 5.2.8 on 2025-12-27 13:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='current_hash',
            field=models.CharField(blank=True, editable=False, help_text='SHA-256 hash of this entry (includes prev_hash)', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='prev_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='SHA-256 hash of previous audit log entry', max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['current_hash'], name='tasks_audit_current_57ae8b_idx'),
        ),
    ]
